---
- name: stop apache service
  service:
    name: "{{ apache_service_name }}"
    state: stopped
  notify:
    - start apache service

- name: load customer specific variables
  include_vars:
    file: "{{ camac_customer_variables }}"
  when: camac_customer_variables != ""

- include_tasks: keycloak.yml
  when: camac_keycloak_enable

- name: create download dir for releases
  file:
    state: directory
    path: "{{ camac_releasedir }}/camac"

- name: create tarball dir
  file:
    state: directory
    path: "{{ camac_tarballdir }}"

- name: download camac release tarball
  get_url:
    url: "{{ camac_release }}"
    dest: "{{ camac_tarball }}"
    checksum: "{% if camac_tarball_checksum %}sha256:{{ camac_tarball_checksum }}{% endif %}"

- name: unpack camac tarball
  unarchive:
    src: "{{ camac_tarball }}"
    dest: "{{ camac_releasedir }}/camac"
    remote_src: yes

- name: delete camac release tarballs
  file:
    state: absent
    dest: "{{ camac_tarballdir }}"

- include_tasks: php.yml

- include_tasks: python.yml
  tags: python

- include_tasks: ember.yml
  tags: ember

- include_tasks: document_merge_service.yml
  tags: document_merge_service

- name: clear cache
  command: "php {{ camac_php_docroot }}/cronjob/clear-cache.php"
  tags:
    - cache

- name: remove tmp staging dir
  file:
    state: absent
    dest: "{{ camac_releasedir }}/camac/"
