---
# handlers file for camac

- name: restart wildfly
  service:
    name: wildfly
    state: restarted

- name: restart camac api
  service:
    name: camac-api
    state: restarted

- name: restart camac api q
  service:
    name: camac-api-q
    state: restarted

- name: restart document merge service
  service:
    name: document-merge-service
    state: restarted

- name: start apache service
  service:
    name: "{{ apache_service_name }}"
    state: started

- name: restart systemd daemon
  command: systemctl daemon-reload
