---
# handlers file for camac

- name: restart systemd daemon
  ansible.builtin.command: systemctl daemon-reload

- name: restart wildfly
  ansible.builtin.service:
    name: wildfly
    state: restarted

- name: restart camac api
  ansible.builtin.service:
    name: camac-api
    state: restarted

- name: restart camac api q
  ansible.builtin.service:
    name: camac-api-q
    state: restarted

- name: restart document merge service
  ansible.builtin.service:
    name: document-merge-service
    state: restarted

- name: start apache service
  ansible.builtin.service:
    name: "{{ apache_service_name }}"
    state: started

- name: load sysctl config
  ansible.builtin.shell:
    cmd: "sysctl --system"
