---
# handlers file for camac

- name: restart wildfly
  service:
    name: wildfly
    state: restarted

- name: restart camac api
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - camac-api
    - camac-api-q

- name: restart document merge service
  service:
    name: document-merge-service
    state: restarted
